name: Module test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: test module code
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -recursive -check
